configure.ac
gtk3/toolbar/Makefile.am
gtk3/toolbar/applet-gnome3.c
gtk3/toolbar/uim-applet-menu.xml
po/POTFILES.in

Currently, uim does not build with gnome-panel (and libpanel-applet) 3.14, as the library API has changed significally. This PR attempts to fix it.
Note that I am not a user of uim and thus have not tested it properly.
References:
* https://wiki.gnome.org/HowDoI/GAction
* https://wiki.gnome.org/HowDoI/ApplicationMenu
* [gnome-panel 3.14 announce](https://mail.gnome.org/archives/gnome-announce-list/2014-October/msg00036.html)

Port to GAction and libpanel-applet 3.14

---

configure.ac

$enable_debug is either "yes" or "no", so "test -z" is always false

configure.ac: fix a check of debug flag for #qt3

---

gtk2/dict/word-win-gtk.c
po/fr.po
po/ja.po
po/ko.po

They are found by Debian Lintian: spelling-error-in-binary

fix "empty" typo

---

ChangeLog.old
ChangeLog.old.2
doc/ENV
doc/api-doc/uim-devel.db
xim/main.cpp

They are found by Debian Lintian: spelling-error-in-binary

fix "occurred" typo

---

gtk2/pad/ja.c

forwarding from https://bugs.debian.org/787824
this patches are created by "Yuriy M. Kaminskiy" <yumkam@gmail.com>.
----
When uim-input-pad-ja (both gtk2 and gtk3 versions) is running for a 
long time, it triggers growing memory consumption in uim-helper-server, 
as it opens socket to uim-helper-server, but fails to process incoming 
messages (it only uses this socket to write new messages).
Attached patch tries to fix this by adding dummy read handler (it is not
possible to half-close connection, as uim-helper-server will close
connection in this case).
Note: this bug also affects upstream master branch and many/all older 
versions.

fix stuck messages to uim-input-pad-ja

---

uim/socket.c
uim/uim-helper-client.c

forwarding from https://bugs.debian.org/787208 .
these patches are created by "Yuriy M. Kaminskiy" <yumkam@gmail.com>.
----
When uim client exec() to long-running process (e.g. iceweasel 
restarts), it leaks open socket to uim-helper-server, and by then 
uim-helper-server begins to constantly consume memory, as it cannot 
write to those sockets and have to infinitely buffer unsent messages to 
them:
```
strace -p `pidof uim-helper-server`|egrep '^(select|mremap)' ...
select(11, [0 1 3 4 5 6 7 9 10], [1], NULL, NULL) = 1 (in [0])
select(11, [0 1 3 4 5 6 7 9 10], [1 4 5 6 7 9 10], NULL, NULL) = 6 (out 
[4 5 6 7 9 10])
note: here fd 1 points to unix-domain-socket to such iceweasel
process, and it never returns "writeable" status; there are another
socket to same iceweasel process {which was …
```

plug leak to unclosed socket after exec() in client

---

qt5/immodule/quimplatforminputcontextplugin.pro.in

Because DESTDIR variable's null, configure script will ignore qt5 lib
path. We set it to empty variable can make it pass qt5 lib path.

Add DESTDIR variable for qt5 inputcontext lib.

---

gtk2/immodule/uim-cand-win-gtk.c

I fixed the problem that the candidate windows is not shown in GTK3  applications on Fedora 22.

Fix candidate window problem

---

qt4/immodule/plugin.h

Qt5.5 does not load libuimplatforminputcontextplugin.so that has IID `"org.qt-project.Qt.QPlatformInputContextFactoryInterface"` but works with IID `"org.qt-project.Qt.QPlatformInputContextFactoryInterface.5.1"`.
It works fine using `QPlatformInputContextFactoryInterface_iid` instead of fixed string. 
This issue is same as fcitx's issue below:
https://github.com/fcitx/fcitx-qt5/issues/6

Fixed the IID definition to work with Qt5.5.

---

gtk2/immodule/uim-cand-win-vertical-gtk.c

created-by: NaofumiHonda
----
Around the line 209 in gtk2/immodule/uim-cand-win-vertical-gtk.c, the code assumes that the conditions path_currently_selected == false and cwin->candidate_index != idx only hold for the case that a candidate is selected by a mouse click.
Surely this assumption is true for gkt2 case. However, in gtk3 case, the same conditions also hold when the candidate window becomes hidden by changing a target word, which causes a wired phenomenon.
Therefore we need to consider the latter case also and it has been done in the attached patch.
Of course, this patch respects the commitment bc40465 for SEGV.

fix cannot select candidate on GTK3 application, closes #77

---

qt4/candwin/abstractcandidatewindow.cpp
qt4/candwin/subwindow.cpp
qt4/candwin/ximcandidatewindow.cpp
qt4/immodule/candidatewindowproxy.cpp
qt4/immodule/plugin.cpp
qt4/immodule/qtextutil.cpp
qt4/immodule/quiminputcontext_compose.cpp
qt5/immodule/quimplatforminputcontext.cpp
qt5/immodule/quimplatforminputcontext.h

Created-by: NaofumiHonda
----
The reason of the issue is that: the uim-candwin-qt5 also load the uim-plugin, and the loaded plugin again executes uim-candwin-qt5, which causes infinite loops! So it suffices to block this recursive execution.

Fix qt5 candwin infinite loop, closes#30

---

gtk2/immodule/gtk-im-uim.c
qt4/immodule/qhelpermanager.cpp
qt4/immodule/qhelpermanager.h
qt4/immodule/quiminputcontext.cpp
qt5/immodule/quimplatforminputcontext.cpp
uim/uim-helper-client.c
uim/uim-helper.c
uim/uim-helper.h
uim/uim-internal.h
uim/uim.c

* uim/uim-internal.h, uim/uim.c : struct uim_context_ has uim_fd for helper system.
* uim/uim-helper.c, uim/uim-helper.h
* (uim_set_uim_fd): new function
* (uim_unset_uim_fd): new function
* gtk2/immodule/gtk-im-uim.c (check_helper_connection) : add uim_context arg.
* qt4/immodule/qhelpermanager.cpp (QUimHelperManager::checkHelperConnection) : add uim_context arg.

fix global variablel uim_fd, closes #87

---

scm/skk.scm

With AZIK, "hq" should correspond to "hai" in any condition.
However, with the previous code, direct state and kanji state behaves
differently against "hq".
The former inserts "hai" correctly, but in kanji state,
"q" is regarded as kana-toggle key.
This patch fixes this problem.

Check key is not expected in skk-proc-state-kanji

---

configure.ac
gtk3/toolbar/Makefile.am
gtk3/toolbar/UimApplet.panel-applet.in.in
gtk3/toolbar/applet-gnome3.c
gtk3/toolbar/org.gnome.panel.applet.UimAppletFactory.service.in

GNOME Panel 3.22 was released recently with the new version of library, libpanel-applet2. There are some changes required to make uim build/work with this new version.
* Port from out-of-process applet to in-process applet.
* Get the applets directory from pkg-config instead of using the hard-coded path.
See [this link] for details. This code should still work with the previous versions of GNOME Panel (3.14+).
On Debian, the new `libpanel-applet-dev` package is available in experimental.
[this link]: https://mail.gnome.org/archives/gnome-flashback-list/2016-July/msg00000.html

Make the GNOME Panel applet compatible with libpanel-applet2

---

gtk3/toolbar/Makefile.am

To have only a `.so` file, not also `.so.X`, `.so.X.Y` and `.so.X.Y.Z`.
This is a minor addition to my previous pull request.

Link the panel applet plugin with -module -avoid-version

---

qt5/immodule/quimplatforminputcontextplugin.pro.in

When using it, we get the following error when running qmake on Ubuntu 17.10 with Qt 5.9.0 ([full build log](https://launchpadlibrarian.net/324642605/buildlog_ubuntu-artful-amd64.uim_1%3A1.8.6+gh20161003.0.d63dadd-2ubuntu3~ppa1_BUILDING.txt.gz)):
Project ERROR: Could not find feature reduce_exports.
The Qt developers say in [QTBUG-58150](https://bugreports.qt.io/browse/QTBUG-58150):
> this file [qt_plugin.prf] is very clearly marked as *private* and you have no business using it unless you're creating a qt module.

Do not use private qt_plugin.prf in quimplatforminputcontextplugin.pro

---

qt5/immodule/quimplatforminputcontext.cpp
qt5/immodule/quimplatforminputcontext.h

After applying the patch which fixes the issue 112, we sometimes observe the following strange behavior of a candidate window in qt5.
1) First invoke some qt5 program like kwrite, 
2) Then input some (preeidt) string and type the conversion key several times very quickly, and as soon as possible,  cancel them by hitting ESC. 
As a result, the candidate window is cancelled before its pop-up (so you never see the candidate window). 
3) Now, once focus out to other window and then focus in to the original window, 
4) Then the candidate window appears unexpectedly.
This is due to a timing issue between "pop-up" vs "hide" operations of a candidate window,
and this request resolves the issue.

Fix an unexpected behavior of a candidate window after my patch.

---

qt4/toolbar/CMakeLists.txt

pass `-D_FORTIFY_SOURCE=2` to qt5 immodule for hardening. see: https://wiki.debian.org/Hardening

pass CPPFLAGS to CMAKE_CXX_FLAGS for hardening

---

qt5/immodule/quimplatforminputcontext.cpp

Fix debug messages printed to stderr in non-debug builds.
Guessing it was added in during a debugging session and then was never removed.

quimplatforminputcontext.cpp: Remove #define ENABLE_DEBUG

---

configure.ac

"==" operator for test(1) is not in POSIX Standards, just a "=" should be used.

Fix unportable test(1) == operator usage

---

xim/main.cpp

This fixes the following error:
``main.cpp:68:55: error: invalid suffix on literal; C++11 requires a space between literal and identifier``
It have been tested with clang 6.0.1 under gentoo.

xim/main.cpp: Fix building against clang

---

uim/uim-x-util.c

C++ style comment in C may be allowed with C99 or later, but should not be used.

fix c++ style comment usage in c source code

---

replace/os_dep.h

strtonum(3) is an OpenBSD extension on NetBSD-8,
so _OPENBSD_SOURCE must be defined before stdlib.h

Take care strtonum(3) on NetBSD-8

---

qt4/pref/qt4.cpp
qt4/toolbar/common-quimhelpertoolbar.cpp

The qt5 version of uim tries to invoke helper applications using a hard-coded name that includes `-qt4`, which fails if you don't also have the qt4 version installed.
This patch detects which version of Qt that uim is being built with and changes the strings appropriately.

qt5: change hardcoded references to qt4

---

fep/uim-fep.c

The wsl command hangs on uim-fep.
$ uim-fep -e /mnt/c/windows/system32/cmd.exe /c dir
The cause of the hang is unknown, but could be fixed by writing the input data to the pty at once.

fixes a bug that causes the wsl command to hang on uim-fep

---

gtk2/switcher/gtk.c

I found that the immediate cause of the bug #161 is `save_default_im()` in `gtk2/switcher/gtk.c` does not check if the return value of `get_selected_im_name()` is NULL, and the value is dereferenced by `symbol_name_hash()` in `sigscheme/src/symbol.c`.
I could solve this problem by adding early return from `save_default_im()` when `im_name` is NULL.

Fix uim-im-switcher-gtk3 crash when input method list is empty

---

gtk2/toolbar/standalone-gtk.c

`uim-toolbar-gtk3` (and probably `uim-toolbar-gtk` also does) accepts any mouse button to grab window.
But right click is also used to open context menu.
When we do right click on toolbar, context menu is opened, and toolbar is grabbed.
I fixed this bug by ignoring mouse button events unless the event is invoked by left click.
NOTE: With this fix, `button_press_event_cb()` will ignore any clicks other than left click. (so, middle click is also ignored)
This is because I thought middle click (and undo/redo button in many mice) is usually not used to grab window.

Fix uim-toolbar-gtk3 not to be grabbed by right click

---

scm/uim-help.scm

URLs returned by select-url-from-im was like `https://github.com/uim/uim/wikiUimNameOfIM`,
but appropriate URL is `https://github.com/uim/uim/wiki/UimNameOfIM`. (added a slash between `wiki` and `UimNameOfIM`.)

Fix select-url-from-im to return appropriate URL

---

Makefile.am
autogen.sh
configure.ac
gtk2/toolbar/Makefile.am
gtk3/toolbar/Makefile.am

This changes the build system such that passing --disable-nls disables
the requirement for intltool.

Add support for building with --disable-nls without intltool

---

scm/im-custom.scm
xim/convdisp.cpp

This change moves the default fontset definitions to im-custom.scm so
that users may define the fontsets and avoid stderr being filled with:
Critical: XCreateFontSet failed!
Users can override fontsets in ~/.uim or under ~/.uim.d/customs.
Packagers may choose to ship with different fontsets by changing the
defaults under ${datarootdir}/uim.

uim-xim: Don't hardcode fontsets at compile-time

---

fep/escseq.c
fep/escseq.h
fep/uim-fep.c

Two bugs have been fixed.
1 The color of preedit of uim-fep is not correct on 24bit color-capable vim.
When the -c option of uimfep is not specified, uim-fep does not set the foreground color and background color when drawing the preedit.  If you use a vim that supports 24-bit color as shown in the figure below, the background color of uim-fep's preedit and status line will be the color of the vim's status line.
Therefore, even if foreground color and background color are not specified, the default color is set when drawing uim-fep's preedit. After the fix, the color of the preedit and status line will not be the color of the vim status line as shown below.
2 If the app uses 24bit color, the color will change after uim-fep's preedit drawing.
The following figure shows the situation where …

uim-fep 24bit color support

---

fep/key.c
fep/uim-fep.c
fep/uim-fep.h

In neovim, the terminal emulator inputs an escape sequence when a window is unfocused or focused. The escape sequence is now passed directly to the application (neovim) instead of being passed to the uim key input.
In neovim, keystrokes using shift, control and Alt are entered in the format of xtmodkeys from the terminal emulator. For example, shift + a is input as ESC [ 65; 2u in mintty and ESC [ 27; 2; 65~ in xterm. This input is converted to Shift + a and passed to uim.

uim-fep: neovim support

---

configure.ac

C99 removed support for implicit function declarations.  The test calls the undeclared exit function, so it may fail incorrectly with C99 compilers.  Return from main instead to report the test result.

configure: Fix snprintf check for strict(er) C99 compilers

---

examples/uim-custom/uim-custom-variable.c

As found by DCS `[^._]sizeof[ (]'.{1,2}' filetype:c`
Ref: https://paste.sr.ht/~nabijaczleweli/6ee9ccf301a2651afb693bff46e3671d3f7cdd89
Ref: https://101010.pl/@nabijaczleweli/111587138076843793

sizeof('c')=4, not 1: fix overallocation

---

qt3/immodule/quiminputcontext_compose.cpp
qt4/immodule/quiminputcontext_compose.cpp

It is required to cast for the argment, not return value.

Fix cast usage for `isspace`

---

gtk2/immodule/caret-state-indicator.c

Commit 334238f595e223e37da32959f58d6e6dbce53de1 added code to draw a frame. I think commit 59dab654dc4a948efb6e786808dcce7a5d019c07 made it unnecessary by adding a frame widget.
Fix #203.

gtk-immodule: Don't draw an indicator yourself

---

m4/ax_path_qmake4.m4

The check was for dpkg-architecture, but actually running it would elide the "i".
Detected on Gentoo (!!!) with dpkg coincidentally installed, because it is logged as a QA warning:
```
* QA Notice: command not found:
*
*      ./configure: 19734: dpkg-archtecture: not found
*      ./configure: 19942: dpkg-archtecture: not found
```

configure: fix typo in command name that prevented effectively running

---

qt3/chardict/unicodeviewwidget.cpp

It was introduced on converting from fixed block size, not happend in qt4.

uim-chardict-qt3: fix an off-by-one error

---

configure.ac
replace/getpeereid.c

I don't know why not using `AC_CHECK_TYPES` for other struct type detection, but it is sufficient for `struct sockcred`.

configure: detect struct sockcred

---

replace/os_dep.h

It may be already defined with autoconf or users.

Avoid to redefine _OPENBSD_SOURCE on NetBSD

---

uim/uim-helper-client.c
uim/uim-helper-server.c

It is required for platforms missing `getpeereid()` and suppliment function is implemented with `LOCAL_CREDS`.
(NetBSD-5.0 and later have the function, so not "for NetBSD")
Fixed random unwanted behaviour on recent NetBSD.

uim-helper: fix `LOCAL_CRED` usage condition

---

qt4/chardict/unicodeviewwidget.cpp

`QChar` is 16-bit charactor, so surrogate pairs must be handled properly.

uim-chardict-qt4: fix to display surrogate pairs

---

qt4/chardict/qt4.cpp

Qt>=4.7 has the way to ask the window manager to not geve focus.

uim-chardict-qt4: prevent input focus with Qt way

---

m4/openssl.m4

C99 removed support for implicit function declarations. Same thing as 99fd890fa601b81ff99e5e0f1977fe309f56b90e but for other functions.

m4: fix OpenSSL checks for strict(er) C99 compilers

---

qt4/immodule/candidatewindowproxy.cpp

This is an amendment to #218.
Currently qt5 candidate window is used on top of qt6 applications.

Use qt6 candidate window

---

gtk3/pref/gtk.c

This fixes gtk3 module not building

gtk3: remove leftover #endif

---

gtk3/candwin/gtk.c
gtk3/dict/word-list-view-gtk.c
gtk3/immodule/uim-cand-win-vertical-gtk.c
gtk3/pref/gtk.c
gtk3/switcher/gtk.c

Because it's deprecated since GTK 3.14.

gtk3: don't use gtk_tree_view_set_rules_hint()

---

qt3/candwin/Makefile.am
qt3/chardict/Makefile.am
qt3/pref/Makefile.am
qt3/switcher/Makefile.am
qt3/toolbar/Makefile.am

It wad dropped in coverting to use AM_CPPFLAGS and required for "qtgettext.h".

qt3: fix missing include path

---

uim/uim-helper.c
uim/uim-helper.h

It's useful to maintain helper file descriptor by
`uim_{set,unset}_uim_fd()`. If we also have getter, we can use `uim_helper_send_message()` with file descriptor maintained by `uim_{set,unset,get}_uim_fd()`.

uim_get_uim_fd: add

---

.github/workflows/linux.yml
ci/dockerfiles/debian-13-core.dockerfile
ci/dockerfiles/debian-13-gtk2.dockerfile
ci/dockerfiles/debian-13-gtk3.dockerfile
ci/dockerfiles/debian-13-qt5.dockerfile
ci/dockerfiles/debian-13-qt6.dockerfile
ci/dockerfiles/debian-13-tqt.dockerfile
compose.yaml

It's the current stable.
If we use Debian 13 for release, we got the #221 error. We will revisit it later.

ci: Use Debian 13 except release image
