- uim.desktop.in.in
a Keywords field required by desktop entry specification.
- http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html
- https://bugs.debian.org/693918
- https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords
> add keywords to application desktop files

- qt4/immodule/plugin.cpp
> fix build error Qt 5.1.1

- gtk2/dict/word-list-win-gtk.c
- gtk2/dict/word-win-gtk.c
- po/fr.po
- po/ja.po
- po/ko.po
> fix "information" and "succeeded" typos and update po files

- qt4/immodule/candidatewindowproxy.cpp
> fix uim-candwin-qt5 infinite loop bug (add missing part)

- scm/skk.scm
> Revert "Check key is not expected in skk-proc-state-kanji"

- gtk2/toolbar/common-gtk.c
> do not use GtkWidget-focus-* deprecated since GTK 3.14

- test2/Makefile.am
do not use run singletest.sh (workaround)
> enable to build with automake 1.15

- qt4/toolbar/common-quimhelpertoolbar.cpp
> fix preference icon is not displayed on qt4/5 toolbar

- qt5/immodule/quimplatforminputcontext.cpp
> delays a creation of candwin instance until it is really needed

- emacs/README
It took me all morning to figure out. I hope it saves someone else's
time.
> document incompatibility with evil

- gtk2/immodule/Makefile.am
- gtk3/immodule/Makefile.am
- uim/Makefile.am
Created by Yuriy M. Kaminskiy <yumkam+debian@gmail.com>
> avoid a useless dependency

- po/POTFILES.in
- po/fr.po
- po/ja.po
- po/ko.po
> remove social-ime from po

- emacs/uim.el
> emacs: Add autoload cookies for `uim-mode' and `uim-mode-switch'.

- fep/escseq.c
- fep/uim-fep.h
Fix some portablity issues for out of the GNU world.
> Improve term portability

- emacs/uim-helper.el
- emacs/uim.el
see https://www.gnu.org/software/emacs/news/NEWS.22.1 and https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=f1c48b0ec521744826ed43ae27eed0e152c472bf
> replace process-kill-without-query with set-process-query-on-exit-flag

- uim/skk.c
GitHub: fix GH-175
Reported by toshjp. Thanks!!!
> skk: Fix numeric converted string not null terminated

- NEWS
It should not be same as above entry.
> Fix a issue reference in 1.8.9 entry

- uim/uim-xkb.c
> Fix crash in Qt5 apps in Wayland

- qt3/pref/Makefile.am
- qt3/pref/customwidgets.cpp
* missing caption setting
* translation for labels
> Fix some UI based dialog issues for Qt3

- configure.ac
> configure: Support anthy-unicode

- gtk3/candwin/Makefile.am
- gtk3/candwin/gtk.c
- gtk3/immodule/uim-cand-win-gtk.h
> gtk3 candwin gtk: reuse immodule/uim-cand-win-vertical-gtk.h

- configure.ac
Priority:
1. gtk3
2. qt6
3. qt5
4. gtk
5. qt4
6. qt
> configure: change the default --enable-default-toolkit to auto
